name: deepresearchagent
cmd: ["/home/nn/miniconda3/envs/deepresearch/bin/python", "agent_runner.py"]
cwd: /home/nn/SOTA-agents/DeepResearchAgent
# exp_id: deepresearchagent-kimi-k2
exp_id: deepresearchagent-claude-sonnet-4.6
# model_name: kimi-k2-0905-preview
model_name: openai/claude-sonnet-4-6
agent_type: deepresearchagent
concurrency: 5
timeout: 1500
data_dir: /home/nn/SOTA-agents/RolloutRunner/data
