name: openrca
cmd: ["/home/nn/SOTA-agents/OpenRCA/.venv/bin/python", "agent_runner.py"]
cwd: /home/nn/SOTA-agents/OpenRCA
# exp_id: openrca-kimi-k2
exp_id: openrca-claude-sonnet-4.6
# model_name: kimi-k2-0905-preview
model_name: openai/claude-sonnet-4-6
agent_type: openrca
concurrency: 5
timeout: 1200
data_dir: /home/nn/SOTA-agents/RolloutRunner/data
