name: thinkdepthai
cmd: ["/home/nn/SOTA-agents/Deep_Research/.venv/bin/python", "agent_runner.py"]
cwd: /home/nn/SOTA-agents/Deep_Research
# exp_id: thinkdepthai-kimi-k2
exp_id: thinkdepthai-claude-sonnet-4.6
# model_name: doubao-seed-2-0-pro-260215
# model_name: kimi-k2-0905-preview
model_name: openai/claude-sonnet-4-6
agent_type: thinkdepthai
concurrency: 5
timeout: 1200
data_dir: /home/nn/SOTA-agents/RolloutRunner/data
